version: "3"

services:

    server:
        container_name: numbertheorynode
        build:
            context: ./numbertheorynode
            dockerfile: dev.dockerfile
        ports:
            - 5001:5001
        volumes:
            - ./numbertheorynode:/src/server/app
        working_dir: /src/server/app
        env_file:
            - ./numbertheorynode/.env
    
    client:
        container_name: numbertheroyreact
        build:
            context: ./numbertheroyreact
            dockerfile: dev.dockerfile
        environment:
            HOST: 0.0.0.0
        ports:
            - 5003:5003
        volumes:
            - ./numbertheroyreact:/src/client/app
        working_dir: /src/client/app
        env_file:
            - ./numbertheroyreact/.env